[pytest]
# this represents our tests directory path
testpaths = ./tests
# addopts are pytest arguments
addopts = -v --tracing=retain-on-failure
# what kind of names it should look for
python_files = test_*.py